# Generated by Django 4.0.3 on 2022-03-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeCalorieCounter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='carbohydrate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='food',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
