# Generated by Django 4.0.3 on 2022-03-28 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FreeCalorieCounter', '0005_remove_profile_carbohydrate_remove_profile_fats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfood',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='postfood',
            name='calorie_amount',
        ),
        migrations.RemoveField(
            model_name='postfood',
            name='carbohydrate',
        ),
        migrations.RemoveField(
            model_name='postfood',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='postfood',
            name='protein',
        ),
    ]
