# Generated by Django 4.0.3 on 2022-03-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeCalorieCounter', '0006_remove_postfood_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfood',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='postfood',
            name='calorie_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='postfood',
            name='carbohydrate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='postfood',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='postfood',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
