# Generated by Django 4.0.3 on 2022-03-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeCalorieCounter', '0007_postfood_amount_postfood_calorie_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='carbohydrate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
